name: DenoDeploy

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: yud0uhu
          entrypoint: main.ts
        env:
          DEPLOY_TOKEN: ${{ secrets.DENO_DEPLOY_TOKEN }}